spring:
  application:
    name: sns-api
  datasource:
    url: jdbc:mysql://localhost:3306/sns?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate  # Entity와 실제 DB 스키마 검증
    show-sql: true  # SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # SQL 포맷팅
        use_sql_comments: true  # SQL 주석 출력
        jdbc.time_zone: Asia/Seoul
  data:
    redis:
      host: localhost
      port: 6379

app:
  messaging:
    post:
      created-routing-key: post.created
      deleted-routing-key: post.deleted

spring.rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

