spring:
  application:
    name: sns-api
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc.time_zone: Asia/Seoul
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

app:
  messaging:
    post:
      created-routing-key: post.created
      deleted-routing-key: post.deleted

spring.rabbitmq:
  host: ${RABBITMQ_HOST}
  port: ${RABBITMQ_PORT:5672}
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}

